### ISSUE TITLE
PyPI no longer requires reStructuredText

### ISSUE THREAD

**Issue by netserf** [bast/somepackage#5]
You may want to update your README section on **Documentation**. 

PyPI no longer requires reStructuredText. You can use Markdown as noted on https://pypi.org/help/ under **How can I upload a project description in a different format?**

Example shown here: https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

Thanks for the notes on how to structure a python packages.

**Comment by bast** [comment]
dear Greg, thank you for pointing this out! I will adjust the documentation to reflect this within the following days.

**Comment by bast** [comment]
Thanks again!
